[package]
org = "ballerina"
name = "xslt"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["xslt", "xml", "html", "xsl", "transformation"]
repository = "https://github.com/ballerina-platform/module-ballerina-xslt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xslt-native"
version = "@toml.version@"
path = "../native/build/libs/xslt-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-@jakarta.activation.version@.jar"
version = "@jakarta.activation.version@"
