[package]
org = "ballerina"
name = "xslt"
version = "2.2.3"
authors = ["Ballerina"]
keywords = ["xslt", "xml", "html", "xsl", "transformation"]
repository = "https://github.com/ballerina-platform/module-ballerina-xslt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xslt-native"
version = "2.2.3"
path = "../native/build/libs/xslt-native-2.2.3-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
version = "1.2.2"
